# Generated by Django 2.0.7 on 2018-11-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_auto_20181124_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
