# Generated by Django 2.0.7 on 2018-09-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0005_anodelog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcg',
            name='serial_num',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
