# Generated by Django 2.0.7 on 2018-10-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palm', '0007_auto_20181006_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anode',
            name='serial_num',
            field=models.CharField(max_length=100),
        ),
    ]
