# Generated by Django 2.0.7 on 2018-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.GenericIPAddressField(default=None),
            preserve_default=False,
        ),
    ]
